development:
  host: localhost
  adapter: postgresql
  database: HuddleUp
  username: postgres
  password: pentag0n

test:
  host: localhost
  adapter: postgresql
  database: HuddleUp_Test
  username: postgres
  password: pentag0n

